image: maven:3.9-eclipse-temurin-21

stages:
  - build
  - test
  - sast
  - package
  - sca-package
  - publish
  - sca-container
  - deploy
  - fuzzing
  - dast
  - bundle

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/todolist
  IMAGE_TAG: latest
  FUZZING_TARGET: "http://10.97.15.178:8080"
  DAST_TARGET: "http://10.97.15.178:8080"

build:
  stage: build
  script:
    - java -version
    - mvn -version
    - mvn clean compile

unit-test:
  stage: test
  script:
    - echo "Running Unit Tests..."
    - mvn test

integration-test:
  stage: test
  script:
    - echo "Running Integration Tests..."
    - mvn verify -Dskip.surefire.tests=true

sast-semgrep:
  stage: sast
  image: returntocorp/semgrep
  script:
    - mkdir -p reports
    - semgrep scan --config=auto --json --output=reports/gl-sast-report.json .
  artifacts:
    paths:
      - reports/gl-sast-report.json
    expire_in: 1 week
    when: always
  allow_failure: true

sast-gitleaks:
  stage: sast
  image:
    name: zricethezav/gitleaks:latest
    entrypoint: [""]
  script:
    - mkdir -p reports
    - gitleaks detect --source="$CI_PROJECT_DIR" --report-format=json --report-path=reports/gl-secret-detection-report.json --exit-code=0
  artifacts:
    paths:
      - reports/gl-secret-detection-report.json
    expire_in: 1 week
    when: always
  allow_failure: true

package-jar:
  stage: package
  script:
    - echo "Packaging Todo List into a JAR..."
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour

sca-package-dependency-check:
  stage: sca-package
  image:
    name: owasp/dependency-check:latest
    entrypoint: [""]
  cache:
    key: dependency-check-nvd-db
    paths:
      - odc-data/
  script:
    - mkdir -p reports
    - mkdir -p odc-data
    - |
      /usr/share/dependency-check/bin/dependency-check.sh \
        --scan . \
        --data ./odc-data \
        --format JSON \
        --format HTML \
        --out reports \
        --nvdApiKey "$NVD_API_KEY" \
        --disableOssIndex 
  artifacts:
    when: always
    paths:
      - reports/
  allow_failure: true


publish-container:
  stage: publish
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"


publish-package:
  stage: publish
  needs:
    - job: package-jar
      artifacts: true
  script:
    - |
      cat > settings.xml <<'EOF'
      <settings>
        <servers>
          <server>
            <id>gitlab-maven</id>
            <configuration>
              <httpHeaders>
                <property>
                  <name>Job-Token</name>
                  <value>${env.CI_JOB_TOKEN}</value>
                </property>
              </httpHeaders>
            </configuration>
          </server>
        </servers>
      </settings>
      EOF
    - mvn -s settings.xml deploy -DskipTests -Dmaven.install.skip=true || echo "Skipped remote deploy"


sca-container-trivy:
  stage: sca-container
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  before_script:
    - trivy image --download-db-only
    - echo "$CI_REGISTRY_PASSWORD" | trivy registry login --username "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - mkdir -p reports
    - trivy image --format json --output reports/trivy-report.json --exit-code 0 $CI_REGISTRY_IMAGE:latest
  artifacts:
    paths:
      - reports/trivy-report.json
    expire_in: 1 week
    when: always
  allow_failure: true

