stages:
  - build
  - package
  - test
  - publish
  - deploy

test-job:
  stage: test
  script:
    - echo "Group runner works!"

build:
  stage: build
  script:
    - java -version
    - mvn clean compile

package:
  stage: package
  script:
    - echo " Packaging Todo List into a JAR..."
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour